apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
      chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: db
  selector:
      app: mongo-db
