apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  serviceName: "mongo-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: "{{ .Values.mongo.image }}"
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClassName | default "gp2" }}
      resources:
        requests:
          storage: "2Gi"