apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.name }}
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "extensions", "policy"]
    resources: ["deployments", "services", "configmaps", "secrets", "ingresses", "poddisruptionbudgets", "statefulsets", "namespaces"]
    verbs: ["create", "get", "watch", "list", "patch", "update", "delete"]
