apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.github_org }}-runners
subjects:
  - kind: ServiceAccount
    name: {{ include "github-actions-runners.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.github_org }}-runners
  apiGroup: rbac.authorization.k8s.io
