apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.github_org }}
spec:
  scaleTargetRef:
    name: {{ .Values.github_org }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas}}
  scaleUpTriggers:
    - githubEvent:
        checkRun:
          types: [ "created" ]
          status: "queued"
      amount: {{ .Values.scaleAmount }}
      duration: {{ .Values.scaleDuration }}
