apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dockerdContainerResources }}
      dockerdContainerResources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.githubOrg }}
      organization: {{ .Values.githubOrg }}
      {{- else if .Values.githubRepo }}
      repository: {{ .Values.githubRepo }}
      {{- end }}
      serviceAccountName: {{ include "github-actions-runners.serviceAccountName" . }}
      securityContext:
        fsGroup: 1447
      automountServiceAccountToken: true
      image: {{ .Values.image }}
