apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.github_org }}-runners
spec:
  replicas: {{ .Values.initialReplicas }}
  template:
    spec:
      {{- if .Values.runner_labels -}}
      labels:
        {{- with .Values.runner_labels -}}
        - {{ . }}
      {{- end }}
      {{- if .Values.dockerdContainerResources -}}
      {{ toYaml .Values.dockerdContainerResources }}
      {{- end }}
      organization: {{ .Values.github_org }}
      serviceAccountName: {{ include "github-actions-runners.serviceAccountName" . }}
      automountServiceAccountToken: true
