variable "region" {}
variable "namespace" {}
variable "vault_dynamodb_table_name" {}
variable "vault_hostname" {}
variable "cert_issuer_name" {}
variable "cert_issuer_kind" {}
variable "vault_aws_access_key_id" {}
variable "vault_aws_secret_access_key" {}
variable "vault_kms_key_id" {}
