replicaCount: 1

image: "artifactory.toolchain.lead.prod.liatr.io/docker-registry/liatrio/grafeas:0.0.1"
pullPolicy: IfNotPresent

nameOverride: "grafeas-server"
fullnameOverride: "grafeas-server"

# The name of persistent volume to use
# persistent volume is used for storing the embedded grafeas data
persistentVolumeClaimName: "grafeas"

# The type of storage used, supported options: memstore or embedded
# REMARK: embedded storage requires a persistent volume
storageType: "memstore"

service:
  type: ClusterIP
  port: 443

container:
  port: 443

# Certificates for mutual authentication
certificates:
  secretname: cert-secret
  enabled: true
  name: grafeas-ssl-certs
  ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessprobe:
  initialDelaySeconds: 15 # Value based on pod startup average of ~12 seconds using default limits above
  periodSeconds: 10
  failureThreshold: 3 # initialDelaySeconds + (failureThreshold * periodSeconds) based on worst case startup time of 45 seconds

readinessprobe:
  initialDelaySeconds: 15 # Value based on pod startup average of ~12 seconds using default limits above
  periodSeconds: 10
  failureThreshold: 3 # initialDelaySeconds + (failureThreshold * periodSeconds) based on worst case startup time of 45 seconds
