cask_args appdir: "/Applications"
tap "homebrew/cask"
brew "terraform"
brew "terragrunt"
brew "kubernetes-cli"
brew "helm@2"
brew "aws-iam-authenticator"
brew "azure-cli"
brew "dnsmasq"
brew "go"

cask "aws-vault"
