apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: attestationauthorities.kritis.grafeas.io
  labels:
    kritis.grafeas.io/install: ""
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: attestationauthorities
    singular: attestationauthority
    kind: AttestationAuthority
