apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagesecuritypolicies.kritis.grafeas.io
  labels:
    kritis.grafeas.io/install: ""
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ImageSecurityPolicy
    plural: imagesecuritypolicies
