apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kritisconfigs.kritis.grafeas.io
spec:
  group: kritis.grafeas.io
  version: v1beta1
  scope: Cluster
  names:
    plural: kritisconfigs
    singular: kritisconfig
    kind: KritisConfig
