storageClassName:
components:
  registry:
    size: 2Gi
    mountPath: "/storage"
    initCommands:
      - "mkdir -p /storage/docker && chown -R 10000:10000 /storage"
    protectPvcResource: true
  database:
    size: 2Gi
    mountPath: "/database"
    initCommands:
      - "echo \"hello\""
    protectPvcResource: true

