{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: kiali
  name: kiali
spec:
  rules:
    - host: "kiali.{{ .Values.domain }}"
      http:
        paths:
          - backend:
              serviceName: kiali
              servicePort: 20001
            path: /
  tls:
    - hosts:
        - "kiali.{{ .Values.domain }}"
{{- end }}
