apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: toolchain-nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: kiali
  name: kiali
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: kiali
              servicePort: 20001
            path: /kiali
  tls:
    - hosts:
        - {{ .Values.host }}
