apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceNamespace }}
  labels:
    app: {{ .Values.serviceName }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ .Values.kritisInstallLabel }}: ""
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    app: {{ .Values.serviceName }}
    release: {{ .Release.Name }}
