apiVersion: v1
kind: List
items:

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: {{ .Values.clusterRoleBindingName }}
    labels:
      {{ .Values.kritisInstallLabel }}: ""
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.serviceNamespace }}
    name: default

# to let the admission server read image allowlist in imagesecuritypolicies
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: {{ .Values.clusterRoleName }}
    labels:
      # Add these permissions to the "edit" default role, so that "edit" can see our CRD.
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
    {{ .Values.kritisInstallLabel }}: ""
  rules:
  - apiGroups: ["kritis.grafeas.io"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["*"]
