apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kritis-validation-hook
  labels:
    kritis.grafeas.io/install: ""
webhooks:
- name: kritis-validation-hook.grafeas.io
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kritis-validation
      operator: NotIn 
      values:
      - disabled
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lSQU5PRk9IR0hONXdkcE9tR3lWY0ZsZHN3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFUU1BNEdBMVVFQ2hNSFRHbGhkSEpwYnpFWk1CY0dBMVVFQXhNUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYnpBZQpGdzB4T1RFd01UVXlNelV4TVRsYUZ3MHlNREF4TVRNeU16VXhNVGxhTURJeEZUQVRCZ05WQkFvVERHTmxjblF0CmJXRnVZV2RsY2pFWk1CY0dBMVVFQXhNUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYnpDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5Wa2cxeXN3cWpWR1dLTnJWbE02VUhrYS9ZS0tyelVWZXhDUFVzdgozZ1J0cnk4bmZLVjd3MDlyTVlZc0J6MVhIT0c1UDZQTXZZeWJ0OHNIanBVZ0VZOXY2eHFYclZkeUZrYUljc1ZFCnRCWEdwSDdvcnI3aXA2bk1VRHNmVVdzYWRUdisrZTJUcEFvOEh2OXpaZm9RNy9oRWFFMDV5RDUyTEIvUzZraXUKM21mRmRkRXJpaUJIZXVlZDRIWHYrZFM4bmh0enVUSisvL2tiMFJkNzExd3hwdGVmSTRSeDlIRURXWWlqTkd1agpMUEtML3lwS1dvc1VtNXZld2NWVmtneURYN3pINnVoaVgwSzJ1NmFDa2R1NXBIMlVQZUNZMGdiZlMxdlc3bjRyClpBeFRCYmRDdEdNSWZ3Q1pkYU43TjBnNXNVam5sSTVSTE4wb2YrbGZFckhhVE1jQ0F3RUFBYU55TUhBd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVWtqZkxJV2dvS3ZYUwpGbXFDd3F1R2h3WThjSGN3THdZRFZSMFJCQ2d3Sm9JUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYjRJU0tpNXpZVzVrClltOTRMbXhwWVhSeUxtbHZNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJOQjh0b2lNSGR0Mk4rb0JQaForNFkKaHdXQ0VzM3pYQnpwWUo4QjF1SHpXTTJSZW5Zbk50RWR1RnpJS3hEMmhaeEJkMXphTHAxYzVWVmNlS2N5dDZIcgpEOTFURVVEcCtnVEdhSjVPYktIQzRJdlBva0pOSHZLL1l1cTNIYjNQTnJKdFZaVVJuNG9saWMzTWoya0xQUzRMCndUaXZmZ2hGUTROWkMzSFRaYUhUaE9raS9SRTl4Zk9oR2xmZEZhWVhSQTVwVjJHZXZubXpndHZNWm1hcS81ZWcKWFpURXFYckdjUTVnc1AzNmV3VkNXeEpNL0RNWjFJN09DTGVrQmsvVU1pMUt5dW1uZGFLWnF5Z3dRQ1N1QVNMWQp0RzVYa3ZnRDdIK0Q3MWxFeFRTdHZGbjlHazQzalF5a1lEQUtKNGREOGMzdVZJM1dnMWlQRkQ4ZE96NUNQNDB2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    service:
      name: "kritis-validation-hook"
      namespace: "{{ .Values.serviceNamespace }}"
