apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kritis-validation-hook
  labels:
    kritis.grafeas.io/install: ""
webhooks:
- name: kritis-validation-hook.grafeas.io
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kritis-validation
      operator: NotIn 
      values:
      - disabled
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lSQUt1UGNNRGVpdXFiRlR3RWZDaE05U1l3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFUU1BNEdBMVVFQ2hNSFRHbGhkSEpwYnpFWk1CY0dBMVVFQXhNUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYnpBZQpGdzB4T1RFd01URXlNelUyTVRkYUZ3MHlNREF4TURreU16VTJNVGRhTURJeEZUQVRCZ05WQkFvVERHTmxjblF0CmJXRnVZV2RsY2pFWk1CY0dBMVVFQXhNUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYnpDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU9lRyszeVRzMGxUbmVuRmtmMU9LM2JuejRMNnAvU21UVHZhN1JnVgo0UGw4cW9rWGR2aDVxcFV1aHVGdlJ5dUs4YnVxa3ZuM01wTzVORENMQzVMaisrYTJKblVsTnpQOXhDMEFDc01MCnhPbExpQzhSWlJWZ1FGaVlUM3gyS0ozMXB4UUVSeW5rZU5DRmZWbG0xbWErYVZ0a2tDdGxlK0pRNkxxdHBkU24KU3hrWVAwL0kzcDRRWW56OWJ4Z1lrSFJTWUxobkRrTFB3SWRMSHVBYVJ2bHJYVXZZekdFQ2JJdENJRDMvbWpVbgpEdUk4RTUvZUN6NmNTclkzQmRzRGFyaGJCL25wUCtDNUgyY2Y1dGdKMHBCbzBGYWpTZTBrcEdLVnRTeDVwSXJvCk5IYlpQZ0hnb1h1bVNkbkJ3bTBVR0QrOElCQ1dHY2kxZUdwUWxsWXNJSE9tRTRNQ0F3RUFBYU55TUhBd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVWtqZkxJV2dvS3ZYUwpGbXFDd3F1R2h3WThjSGN3THdZRFZSMFJCQ2d3Sm9JUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYjRJU0tpNXpZVzVrClltOTRMbXhwWVhSeUxtbHZNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNIRFpWdGhvejl1QVVSKzBBU2hRMEEKVU5FZFJLbEhxN3VoQ0ZrQmhaSmo5WDNadWRuaTY1aXdOZEVRNGloME5oZVVON1UyMkQ3dzlrTUNUcDMra1ptcQpkQkdwdDV3OURLSnFvSFhhekV6Si9XcVZlWGIxenRQL3hlbi9udGlrYVVwRWxEM1drb051eXVTVlRnL3dEQ09JCmRzaldkYjB0eGlmQjRyTzBOMzdDdDVCVTNkSFBJRG5taDdEa0MvV3BNVGQxV0IwRmF1YnBOZ0xPS09TUk9nYkgKdWkrekVQV0pLVkNUU0tDZGdYcGc1SC9uSDYwSDY1dTl3dWF2eG50SUxkRDBBMXJFaG53RmtGRnZrZDZhSWpXKwpxTmVDeUk5ekdaNEN1dzVyZU5WZ3pCZkJnTENmUEVhTERidjhxUHNCc0hsLzhjamxrSW5peWU0ckJqTnhheVBLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    service:
      name: "kritis-validation-hook"
      namespace: "{{ .Values.serviceNamespace }}"
