apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kritis-validation-hook
  labels:
    kritis.grafeas.io/install: ""
webhooks:
- name: kritis-validation-hook.grafeas.io
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kritis-validation
      operator: NotIn 
      values:
      - disabled
  clientConfig:
    caBundle: "-----BEGIN CERTIFICATE——MIIDXDCCAkSgAwIBAgIRANOFOHGHN5wdpOmGyVcFldswDQYJKoZIhvcNAQELBQAwLTEQMA4GA1UEChMHTGlhdHJpbzEZMBcGA1UEAxMQc2FuZGJv    eC5saWF0ci5pbzAeFw0xOTEwMTUyMzUxMTlaFw0yMDAxMTMyMzUxMTlaMDIxFTATBgNVBAoTDGNlcnQtbWFuYWdlcjEZMBcGA1UEAxMQc2FuZGJveC5saWF0ci5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANVkg1yswqjVGWKNrVlM6UHka/YKKrzUVexCPUsv3gRtry8nfKV7w09rMYYsBz1XHOG5P6PMvYybt8sHjpUgEY9v6xqXrVdyFkaIcsVEtBXGpH7orr7ip6nMUDsfUWsadTv++e2TpAo8Hv9zZfoQ7/hEaE05yD52LB/S6kiu3mfFddEriiBHeued4HXv+dS8nhtzuTJ+//kb0Rd711wxptefI4Rx9HEDWYijNGujLPKL/ypKWosUm5vewcVVkgyDX7zH6uhiX0K2u6aCkdu5pH2UPeCY0gbfS1vW7n4rZAxTBbdCtGMIfwCZdaN7N0g5sUjnlI5RLN0of+lfErHaTMcCAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUkjfLIWgoKvXSFmqCwquGhwY8cHcwLwYDVR0RBCgwJoIQc2FuZGJveC5saWF0ci5pb4ISKi5zYW5kYm94LmxpYXRyLmlvMA0GCSqGSIb3DQEBCwUAA4IBAQBNB8toiMHdt2N+oBPhZ+4YhwWCEs3zXBzpYJ8B1uHzWM2RenYnNtEduFzIKxD2hZxBd1zaLp1c5VVceKcyt6HrD91TEUDp+gTGaJ5ObKHC4IvPokJNHvK/Yuq3Hb3PNrJtVZURn4olic3Mj2kLPS4LwTivfghFQ4NZC3HTZaHThOki/RE9xfOhGlfdFaYXRA5pV2GevnmzgtvMZmaq/5egXZTEqXrGcQ5gsP36ewVCWxJM/DMZ1I7OCLekBk/UMi1KyumndaKZqygwQCSuASLYtG5XkvgD7H+D71lExTStvFn9Gk43jQykYDAKJ4dD8c3uVI3Wg1iPFD8dOz5CP40v-----END CERTIFICATE-----"
    service:
      name: "kritis-validation-hook"
      namespace: "{{ .Values.serviceNamespace }}"
