apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kritis-validation-hook
  labels:
    kritis.grafeas.io/install: ""
webhooks:
- name: kritis-validation-hook
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kritis-validation
      operator: NotIn 
      values:
      - disabled
  clientConfig:
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lSQVBiM3BlWXhMMjVKRStGYU1FRjBweUF3RFFZSktvWklodmNOQVFFTEJRQXcKTFRFUU1BNEdBMVVFQ2hNSFRHbGhkSEpwYnpFWk1CY0dBMVVFQXhNUWMyRnVaR0p2ZUM1c2FXRjBjaTVwYnpBZQpGdzB4T1RFd01UWXhPVEE1TkRoYUZ3MHlNREF4TVRReE9UQTVORGhhTUVZeEZUQVRCZ05WQkFvVERHTmxjblF0CmJXRnVZV2RsY2pFdE1Dc0dBMVVFQXhNa2EzSnBkR2x6TFhaaGJHbGtZWFJwYjI0dGFHOXZheTUwYjI5c1kyaGgKYVc0dWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBwVHN3TFlWNUZqaApRMjhic0N0Y3M3eVdVUDBDaFJZZzZMQ2hMeGhYN09sMVBGMlExSnFqWlNaUFZCSUZkb3NiVGdMWE15ZHY1M2VmCktoSzVTS3dhaEFJZ3BnMVlQWjBTSCtQYk04b2ErRTVDT1NJSHJ0VlMyWnova3I2THZ0N3ByaGt3R1VBb2ZwRHAKV1ZJWmNwNzNlWXNZdm5SRC9ac0pkSTFtelFNN1dybFdKQXhza3ZLVFBFNnpTeU1aZXhWeC9CM2FOUy9oaldwSwpSYy9ZTUh6a1RXSVF4elA3djIyQ3IxcG5FaWs0MWJYY0toYUZQbWFKMW54ZjdBMUJETFlWU0VHTnQzZ3ZCWE0xCjhoT3lqWGxOTlk4anlJeXRCUUtYdkNQdnk2VExlQ1dJYWo3SWlmWkpCdGJiNnVLU01NQ0t6LzhidmZxNStjMUEKZUpBREZPaDg0UUlEQVFBQm80R2JNSUdZTUE0R0ExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFQWpBQQpNQjhHQTFVZEl3UVlNQmFBRkpJM3l5Rm9LQ3IxMGhacWdzS3Job2NHUEhCM01GY0dBMVVkRVFSUU1FNkNKR3R5CmFYUnBjeTEyWVd4cFpHRjBhVzl1TFdodmIyc3VkRzl2YkdOb1lXbHVMbk4yWTRJbUtpNXJjbWwwYVhNdGRtRnMKYVdSaGRHbHZiaTFvYjI5ckxuUnZiMnhqYUdGcGJpNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUlocQorRXhTeDl2RUhVUCt4RWQ1YzFFWFVzSndBa2h6WWtCcHVGQ2hmbjFIS1NFN1FCdHZkK2ZYQnhkclV0RkRacWFNCjhOTkRXREJTSjVHWmxjMXZ3OEdXQ1NlRlFXQ2c2MVU5bWdoc01rdHVlb0ZtSCtKanRmaHZFa2xKWFJ4dnFRT08KdkJhTm1uaW11OXdWTFF5Snp1K2JKM2ppZWNhKzJ5SDh2RURFbHZtYWNYNE9PTFlsTnNqZ1NPTHI4UkpERm5kbgppZDQyQ1VralFiWm9Tc3AzNFlHUnFITG14U3hQOW5hQ0tQSks4eHdtWUx5M1pXdGZwdzR5dVF3K0RmSnpaU3ZwClFtak9HZmU3ZHU1VHZvdmE5VUZCM3RsSGZEQmFNckI5ZTNxVEtqMnA4YjFQWm04UEJQNlZtQXZCY0lpZ0MwQ24KTUkxTk1NYk9xQzFaY1NuT2lSTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    service:
      name: "kritis-validation-hook"
      namespace: "{{ .Values.serviceNamespace }}"
