variable "root_zone_name" {}
variable "cluster" {}
variable "namespace" {}
variable "system_namespace" {}
variable "sdm_version" {}
variable "slack_webhook_url" {}
variable "slack_access_token" {}
variable "slack_clientid" {}
variable "slack_clientsecret" {}
variable "slack_verification_token" {}