apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: gratibot-db-daily-backup
  namespace: velero
spec:
  schedule: 0 1 * * *
  template:
    includedNamespaces:
    - 'flywheel-production'
    includedResources:
    - '*'
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - aws-s3
    ttl: 72h0m0s
    labelSelector:
      matchLabels:
        app: gratibot-db
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: outreach-db-daily-backup
  namespace: velero
spec:
  schedule: 0 1 * * *
  template:
    includedNamespaces:
    - 'flywheel-production'
    includedResources:
    - '*'
    snapshotVolumes: true
    storageLocation: default
    volumeSnapshotLocations:
      - aws-s3
    ttl: 72h0m0s
    labelSelector:
      matchLabels:
        app: outreach-db