<?xml version='1.0' encoding='UTF-8'?>
<security version="v10">
  <users>
    <user>
      <username>access-admin</username>
      <password>bcrypt$$2a$08$5ggkROPsFj/TgJ18qcpkMeuj2rmuV983Mgy3MIxlAeUWoydGU9tsa</password>
      <admin>false</admin>
      <enabled>true</enabled>
      <updatableProfile>false</updatableProfile>
      <accountNonExpired>true</accountNonExpired>
      <credentialsExpired>false</credentialsExpired>
      <credentialsNonExpired>true</credentialsNonExpired>
      <accountNonLocked>true</accountNonLocked>
      <realm>internal</realm>
      <transientUser>false</transientUser>
      <groups/>
      <userPropertyInfos/>
      <lastLoginTimeMillis>0</lastLoginTimeMillis>
      <lastAccessTimeMillis>0</lastAccessTimeMillis>
      <locked>false</locked>
    </user>
    <user>
      <username>anonymous</username>
      <admin>false</admin>
      <enabled>true</enabled>
      <updatableProfile>false</updatableProfile>
      <accountNonExpired>true</accountNonExpired>
      <credentialsExpired>false</credentialsExpired>
      <credentialsNonExpired>true</credentialsNonExpired>
      <accountNonLocked>true</accountNonLocked>
      <realm>internal</realm>
      <transientUser>false</transientUser>
      <groups/>
      <userPropertyInfos/>
      <lastLoginTimeMillis>0</lastLoginTimeMillis>
      <lastAccessTimeMillis>0</lastAccessTimeMillis>
      <locked>false</locked>
    </user>
    <user>
      <username>_internal</username>
      <password>bcrypt$$2a$08$cFTqlKlW.cs7Z0BsA2lyAe.4hRt8Ew1Hhh5mmT7MMqv21hu68WuXu</password>
      <admin>false</admin>
      <enabled>true</enabled>
      <updatableProfile>false</updatableProfile>
      <accountNonExpired>true</accountNonExpired>
      <credentialsExpired>false</credentialsExpired>
      <credentialsNonExpired>true</credentialsNonExpired>
      <accountNonLocked>true</accountNonLocked>
      <realm>internal</realm>
      <transientUser>false</transientUser>
      <groups/>
      <userPropertyInfos/>
      <lastLoginTimeMillis>0</lastLoginTimeMillis>
      <lastAccessTimeMillis>0</lastAccessTimeMillis>
      <locked>false</locked>
    </user>
    <user>
      <username>admin</username>
      <password>${admin_bcrypt_pass}</password>
      <admin>true</admin>
      <enabled>true</enabled>
      <updatableProfile>true</updatableProfile>
      <accountNonExpired>true</accountNonExpired>
      <credentialsExpired>false</credentialsExpired>
      <credentialsNonExpired>true</credentialsNonExpired>
      <accountNonLocked>true</accountNonLocked>
      <realm>internal</realm>
      <transientUser>false</transientUser>
      <groups/>
      <userPropertyInfos/>
      <lastLoginTimeMillis>1559856264073</lastLoginTimeMillis>
      <lastLoginClientIp>127.0.0.1</lastLoginClientIp>
      <lastAccessTimeMillis>0</lastAccessTimeMillis>
      <locked>false</locked>
    </user>
    <user>
      <username>jenkins</username>
      <password>${jenkins_bcrypt_pass}</password>
      <email>jenkins@liatr.io</email>
      <admin>false</admin>
      <enabled>true</enabled>
      <updatableProfile>true</updatableProfile>
      <accountNonExpired>true</accountNonExpired>
      <credentialsExpired>false</credentialsExpired>
      <credentialsNonExpired>true</credentialsNonExpired>
      <accountNonLocked>true</accountNonLocked>
      <realm>internal</realm>
      <transientUser>false</transientUser>
      <groups>
        <org.artifactory.model.xstream.security.UserGroupImpl>deployers</org.artifactory.model.xstream.security.UserGroupImpl>
        <org.artifactory.model.xstream.security.UserGroupImpl>readers</org.artifactory.model.xstream.security.UserGroupImpl>
      </groups>
      <userPropertyInfos/>
      <lastLoginTimeMillis>0</lastLoginTimeMillis>
      <lastAccessTimeMillis>0</lastAccessTimeMillis>
      <locked>false</locked>
    </user>
  </users>
  <groups>
    <group>
      <groupName>deployers</groupName>
      <newUserDefault>true</newUserDefault>
      <realm>internal</realm>
      <adminPrivileges>false</adminPrivileges>
    </group>
    <group>
      <groupName>readers</groupName>
      <description>A group for read-only users</description>
      <newUserDefault>true</newUserDefault>
      <realm>internal</realm>
      <adminPrivileges>false</adminPrivileges>
    </group>
  </groups>
  <acls>
    <acl>
      <aces>
        <ace>
          <principal>readers</principal>
          <group>true</group>
          <mask>1</mask>
        </ace>
        <ace>
          <principal>anonymous</principal>
          <group>false</group>
          <mask>1</mask>
        </ace>
      </aces>
      <updatedBy>_system_</updatedBy>
      <lastUpdated>1559840733272</lastUpdated>
      <accessIdentifier>jfrt@01dcpw0zxkn1mf1s69sj3j153g:fb672723-ae39-4681-8249-293bcc624826</accessIdentifier>
      <permissionTarget>
        <name>Anything</name>
        <includes>
          <string>**</string>
        </includes>
        <excludes/>
        <repoKeys>
          <string>ANY</string>
        </repoKeys>
      </permissionTarget>
    </acl>
    <acl>
      <aces>
        <ace>
          <principal>deployers</principal>
          <group>true</group>
          <mask>15</mask>
        </ace>
      </aces>
      <updatedBy>admin</updatedBy>
      <lastUpdated>1559856898049</lastUpdated>
      <accessIdentifier>jfrt@01dcpw0zxkn1mf1s69sj3j153g:10ff2e19-8125-47a1-a2de-3949ea5cb367</accessIdentifier>
      <permissionTarget>
        <name>DeployAny</name>
        <includes>
          <string>**</string>
        </includes>
        <excludes/>
        <repoKeys>
          <string>ANY LOCAL</string>
          <string>ANY REMOTE</string>
        </repoKeys>
      </permissionTarget>
    </acl>
    <acl>
      <aces>
        <ace>
          <principal>anonymous</principal>
          <group>false</group>
          <mask>3</mask>
        </ace>
      </aces>
      <updatedBy>_system_</updatedBy>
      <lastUpdated>1559840733667</lastUpdated>
      <accessIdentifier>jfrt@01dcpw0zxkn1mf1s69sj3j153g:9ba5c95a-4167-43dc-bff9-eb9df1943743</accessIdentifier>
      <permissionTarget>
        <name>Any Remote</name>
        <includes>
          <string>**</string>
        </includes>
        <excludes/>
        <repoKeys>
          <string>ANY REMOTE</string>
        </repoKeys>
      </permissionTarget>
    </acl>
  </acls>
  <buildAcls>
    <buildAcl>
      <aces>
        <ace>
          <principal>readers</principal>
          <group>true</group>
          <mask>1</mask>
        </ace>
        <ace>
          <principal>anonymous</principal>
          <group>false</group>
          <mask>1</mask>
        </ace>
      </aces>
      <updatedBy>_system_</updatedBy>
      <lastUpdated>1559840733573</lastUpdated>
      <accessIdentifier>jfrt@01dcpw0zxkn1mf1s69sj3j153g:18078810-6aa4-4af7-b6ab-3c8d5680197d</accessIdentifier>
      <permissionTarget>
        <name>Anything</name>
        <includes>
          <string>**</string>
        </includes>
        <excludes/>
        <repoKeys>
          <string>artifactory-build-info</string>
        </repoKeys>
      </permissionTarget>
    </buildAcl>
  </buildAcls>
</security>
