apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.postinstall.pod.name }}
  namespace: {{ .Values.serviceNamespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-delete-policy": "hook-failed"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{ .Values.kritisInstallLabel }}: ""
spec:
  restartPolicy: Never
  containers:
  - name: {{ .Values.postinstall.pod.name }}
    image: "{{ .Values.repository }}{{ .Values.postinstall.pod.image }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    args:
      - "--webhook-name"
      - {{ .Values.serviceName }}
      - "--service-name"
      - {{ .Values.serviceName }}
      - "--tls-secret-name"
      - {{ .Values.tlsSecretName }}
      - "--deployment-webhook-name"
      - {{ .Values.serviceNameDeployments }}
      - "--kritis-install-label"
      - {{ .Values.kritisInstallLabel }}
    command: {{ .Values.postinstall.pod.command }}
