apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: toolchain-nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: kibana-ingress
spec:
  rules:
    - host: {{ .Values.kibanaHostname }}
      http:
        paths:
          - backend:
              serviceName: gatekeeper
              servicePort: 3000
            path: /
          - backend:
              serviceName: {{ .Values.upstreamHost }}
              servicePort: {{ .Values.upstreamPort }}
            path: /built_assets
  tls:
    - hosts:
      - {{ .Values.kibanaHostname }}
