apiVersion: v1
kind: Service
metadata:
  labels:
    name: gatekeeper
  name: gatekeeper
spec:
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    name: gatekeeper
