{{- range .Values.components }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-{{ .name }}
  namespace: toolchain
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: harbor
    component: {{ .name }}
    managed-by: Terraform
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: gp2
  volumeMode: Filesystem
{{ end }}
