apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: toolchain
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: harbor
    component: registry
    managed-by: Terraform
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registrySize }}
  storageClassName: gp2
  volumeMode: Filesystem

---

apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-registry-init
spec:
  template:
    metadata:
      name: harbor-registry-init
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: harbor-registry-init
          image: alpine:3.10
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p /storage/docker && chown -R 10000:10000 /storage"]
          volumeMounts:
            - mountPath: /storage
              name: harbor-registry
      volumes:
        - name: harbor-registry
          persistentVolumeClaim:
            claimName: harbor-registry
