apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lead-rules
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
  - name: LEAD
    rules:
    - alert: HostOomKillDetected
      annotations:
        description: Alert for host OOM kill detected.
        summary: Host OOM kill detected.
      expr: increase(node_vmstat_oom_kill[1m]) > 0
      for: 5m
      labels:
        severity: warning
    - alert: KubeClusterAtMaxNodes
      annotations:
        description: Cluster has scaled to its maximum node capacity and cannot tolerate node failure.
        summary: Cluster has reached its node limit.
      expr: count(kube_node_status_condition{condition="Ready", status="true"}) == 35
      for: 5m
      labels:
        severity: critical
