apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  {{- if .Values.acme.enabled }}
  acme:
    config:
    - domains:
      - {{ .Values.domain }}
      - "*.{{ .Values.domain }}"
      dns01:
        provider: liatrio-route53
    commonName: {{ .Values.domain }}
  {{- end  }}
  dnsNames:
  - {{ .Values.domain }}
  - "*.{{ .Values.domain }}"
  issuerRef:
    kind: Issuer
    name: {{ .Values.issuer_name }} 
  secretName: {{ .Release.Name }}-certificate

