apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  annotations:
    "cert-manager.io/issue-temporary-certificate": "true"
spec:
  dnsNames:
  - {{ .Values.domain }}
  - "*.{{ .Values.domain }}"
  {{- if .Values.altname }}
  - {{ .Values.altname }}
  {{- end  }}
  issuerRef:
    kind: {{ .Values.issuer.kind }}
    name: {{ .Values.issuer.name }}
  secretName: {{ .Release.Name }}-certificate
{{- if .Values.waitForCert }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: post-install-job
        image: bitnami/kubectl:1.15
        command: ["/bin/bash", "-c"]
        args: ["until $(kubectl get certificate {{ .Release.Name }} -n {{ .Release.Namespace }} -o jsonpath=\"{.status.conditions[0].status}\" | grep -q \"True\"); do echo \"Waiting...\"; sleep 1; done"]
{{- end  }}
