apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}  
  labels:
    app.kubernetes.io/managed-by: helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lead-system-certificate-watch
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }} 
