module "eks" {
  source                           = "../../../../modules/environment/aws/eks"
  region                           = var.region
  cluster                          = var.cluster_name
  cluster_version                  = var.cluster_version
  cluster_addons                   = var.cluster_addons
  s3_logging_id                    = module.s3-logging.s3_logging_bucket_id
  key_name                         = var.key_name
  spot_instance_types       = var.spot_instance_types
  spot_asg_min_size         = var.spot_asg_min_size
  spot_asg_max_size         = var.spot_asg_max_size
  spot_asg_desired_capacity = var.spot_asg_desired_capacity
  essential_instance_type          = var.essential_instance_type
  essential_asg_max_size           = var.essential_asg_max_size
  essential_asg_min_size           = var.essential_asg_min_size
  essential_asg_desired_capacity   = var.essential_asg_desired_capacity
  essential_taint_key              = var.essential_taint_key
  on_demand_percentage             = "0"
  vpc_name                         = var.vpc_name
  additional_mapped_roles          = var.additional_mapped_roles
  workers_additional_policies      = []
  enable_ssh_access                = var.enable_eks_ssh_access
  docker_registry_mirror           = var.docker_registry_mirror
}
