name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            revert
