name: "Destroy vcluster"

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - master

jobs:

  destroy:
    name: Destroy vcluster
    runs-on: [self-hosted, liatrio-lead-terraform]
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout lead-environments
        uses: actions/checkout@v2
        with:
          repository: liatrio/lead-environments
          path: lead-environments
          token: ${{ secrets.LIATRIO_JENKINS_PAT }}

      - name: Get Branch Name
        id: branch
        uses: tj-actions/branch-names@v5

      - name: Get vcluster Name
        id: vcluster-name
        run: echo "::set-output name=name::${{ steps.branch.outputs.head_ref_branch }}-vcluster"

      - name: Destroy vcluster
        if: github.ref == 'refs/heads/master'
        env:
          VCLUSTER_NAME: ${{ steps.vcluster-name.outputs.name }}
          TERRAGRUNT_IAM_ROLE: ${{ secrets.AWS_LEAD_TERRAFORM_TEST_ROLE }}
        run: terragrunt destroy --terragrunt-working-dir ./lead-environments/aws/vcluster -auto-approve
