name: "Terraform Test"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  VCLUSTER_VERSION: 0.4.3
  TERRAGRUNT_VERSION: 'v0.31.1'

jobs:

  test:
    name: Test
    runs-on: [self-hosted, liatrio-lead-terraform]
    steps:
      - name: Checkout lead-environments
        uses: actions/checkout@v2
        with:
          repository: liatrio/lead-environments
          path: lead-environments
          token: ${{ secrets.LIATRIO_JENKINS_PAT }}

      # aws cli is needed for authenticating to an EKS cluster via terraform
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.0.8

      - name: Setup Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/${{env.TERRAGRUNT_VERSION}}/terragrunt_linux_amd64
          chmod +x ./terragrunt_linux_amd64
          sudo mv ./terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      - name: Get Branch Name
        id: branch
        uses: tj-actions/branch-names@v5

      - name: Get vcluster Name
        id: vcluster-name
        run: echo "::set-output name=name::${{ steps.branch.outputs.head_ref_branch }}-vcluster"

      - name: Download vcluster CLI
        run: |
          curl -LO https://github.com/loft-sh/vcluster/releases/download/v${{env.VCLUSTER_VERSION}}/vcluster-linux-amd64
          chmod +x ./vcluster-linux-amd64
          sudo mv ./vcluster-linux-amd64 /usr/local/bin/vcluster
          vcluster --version

      - name: Create vcluster
        env:
          VCLUSTER_NAME: ${{ steps.vcluster-name.outputs.name }}
          TERRAGRUNT_IAM_ROLE: ${{ secrets.AWS_LEAD_TERRAFORM_TEST_ROLE }}
        run: |
          cd lead-environments/aws/vcluster
          terragrunt apply -auto-approve

      - name: Run Tests
        run: |
          aws sts assume-role --role-arn ${{ secrets.AWS_LEAD_TERRAFORM_TEST_ROLE }} --role-session-name ${{ steps.branch.outputs.head_ref_branch }}-test >> role.json
          export AWS_ACCESS_KEY_ID=$(cat role.json | jq -rc .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(cat role.json | jq -rc .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(cat role.json | jq -rc .Credentials.SessionToken)

          aws eks update-kubeconfig --name lead --region us-east-1

          vcluster connect vcluster --namespace ${{ steps.vcluster-name.outputs.name }} --server https://${{ steps.vcluster-name.outputs.name }}.toolchain.lead.sandbox.liatr.io
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
